/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Mario Garcia Reyes <mgkm10@gmail.com>
 */
public class VistaCita extends javax.swing.JFrame {

    /**
     * @return the apellidodos
     */
    public javax.swing.JTextField getApellidodos() {
        return apellidodos;
    }

    /**
     * @param apellidodos the apellidodos to set
     */
    public void setApellidodos(javax.swing.JTextField apellidodos) {
        this.apellidodos = apellidodos;
    }

    /**
     * @return the apellidouno
     */
    public javax.swing.JTextField getApellidouno() {
        return apellidouno;
    }

    /**
     * @param apellidouno the apellidouno to set
     */
    public void setApellidouno(javax.swing.JTextField apellidouno) {
        this.apellidouno = apellidouno;
    }

    /**
     * @return the textodia
     */
    public javax.swing.JTextField getTextodia() {
        return textodia;
    }

    /**
     * @param textodia the textodia to set
     */
    public void setTextodia(javax.swing.JTextField textodia) {
        this.textodia = textodia;
    }

    /**
     * @return the botoncita
     */
    public javax.swing.JButton getBotoncita() {
        return botoncita;
    }

    /**
     * @param botoncita the botoncita to set
     */
    public void setBotoncita(javax.swing.JButton botoncita) {
        this.botoncita = botoncita;
    }

    /**
     * @return the calendario
     */
    public com.toedter.calendar.JCalendar getCalendario() {
        return calendario;
    }

    /**
     * @param calendario the calendario to set
     */
    public void setCalendario(com.toedter.calendar.JCalendar calendario) {
        this.calendario = calendario;
    }

    /**
     * @return the textohora
     */
    public javax.swing.JTextField getTextohora() {
        return textohora;
    }

    /**
     * @param textohora the textohora to set
     */
    public void setTextohora(javax.swing.JTextField textohora) {
        this.textohora = textohora;
    }

    /**
     * Creates new form VistaCita
     */
    public VistaCita() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectorfichero = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        botoncrear = new javax.swing.JButton();
        botonactualizar = new javax.swing.JButton();
        botonborrar = new javax.swing.JButton();
        textonombre = new javax.swing.JTextField();
        botonimportaralumnos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textoemail = new javax.swing.JTextField();
        textotelefono = new javax.swing.JTextField();
        listadoalumnos = new javax.swing.JComboBox<>();
        calendario = new com.toedter.calendar.JCalendar();
        botoncita = new javax.swing.JButton();
        textodia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textohora = new javax.swing.JTextField();
        hora = new javax.swing.JComboBox<>();
        minutos = new javax.swing.JComboBox<>();
        botonanularcita = new javax.swing.JButton();
        botonactualizarcita = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        botonexportaralumnos = new javax.swing.JButton();
        botonimportarcitas = new javax.swing.JButton();
        botonexportarcitas = new javax.swing.JButton();
        apellidouno = new javax.swing.JTextField();
        apellidodos = new javax.swing.JTextField();
        botonjavadoc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botoncrear.setText("Crear");

        botonactualizar.setText("Actualizar");

        botonborrar.setText("Borrar");

        textonombre.setText("NOMBRE");
        textonombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textonombreActionPerformed(evt);
            }
        });

        botonimportaralumnos.setText("importar alumnos");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Importar BBDD");

        textoemail.setText("EMAIL");

        textotelefono.setText("TELEFONO");

        botoncita.setText("Dar cita");

        jLabel2.setText("Dia");

        jLabel3.setText("Hora");

        hora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", " " }));

        minutos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "5", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55", " " }));

        botonanularcita.setText("Anular cita");

        botonactualizarcita.setText("Actualizar cita");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Cita");

        jLabel7.setText("Hora");

        jLabel4.setText("Minutos");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Seleccion alumno");

        botonexportaralumnos.setText("exportar alumnos");

        botonimportarcitas.setText("importar citas");

        botonexportarcitas.setText("exportar citas");

        apellidouno.setText("PRIMER APELLIDO");

        apellidodos.setText("SEGUNDO APELLIDO");

        botonjavadoc.setText("Abri Javadoc");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(botonimportaralumnos)
                        .addGap(18, 18, 18)
                        .addComponent(botonexportaralumnos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonimportarcitas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonexportarcitas))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(listadoalumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(jLabel5))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(apellidodos, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(apellidouno, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textonombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)))
                                .addGap(53, 53, 53))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoemail, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textotelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(botonactualizar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botoncrear)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botonborrar))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(27, 27, 27)
                                                .addComponent(textodia, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(18, 18, 18)
                                                .addComponent(textohora, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(85, 85, 85)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(minutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botoncita)
                                    .addComponent(botonactualizarcita)
                                    .addComponent(botonanularcita)
                                    .addComponent(botonjavadoc)))
                            .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1)
                                .addGap(230, 230, 230)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botoncita)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonactualizarcita)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(minutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonanularcita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(botonjavadoc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(listadoalumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textonombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(apellidouno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(apellidodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textoemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textotelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonactualizar)
                            .addComponent(botoncrear)
                            .addComponent(botonborrar))
                        .addGap(7, 7, 7)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textodia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textohora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonimportaralumnos)
                    .addComponent(botonexportaralumnos)
                    .addComponent(botonimportarcitas)
                    .addComponent(botonexportarcitas))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textonombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textonombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textonombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidodos;
    private javax.swing.JTextField apellidouno;
    private javax.swing.JButton botonactualizar;
    private javax.swing.JButton botonactualizarcita;
    private javax.swing.JButton botonanularcita;
    private javax.swing.JButton botonborrar;
    private javax.swing.JButton botoncita;
    private javax.swing.JButton botoncrear;
    private javax.swing.JButton botonexportaralumnos;
    private javax.swing.JButton botonexportarcitas;
    private javax.swing.JButton botonimportaralumnos;
    private javax.swing.JButton botonimportarcitas;
    private javax.swing.JButton botonjavadoc;
    private com.toedter.calendar.JCalendar calendario;
    private javax.swing.JComboBox<String> hora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> listadoalumnos;
    private javax.swing.JComboBox<String> minutos;
    private javax.swing.JFileChooser selectorfichero;
    private javax.swing.JTextField textodia;
    private javax.swing.JTextField textoemail;
    private javax.swing.JTextField textohora;
    private javax.swing.JTextField textonombre;
    private javax.swing.JTextField textotelefono;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the botonactualizar
     */
    public javax.swing.JButton getBotonactualizar() {
        return botonactualizar;
    }

    /**
     * @return the botonborrar
     */
    public javax.swing.JButton getBotonborrar() {
        return botonborrar;
    }

    /**
     * @return the botoncrear
     */
    public javax.swing.JButton getBotoncrear() {
        return botoncrear;
    }


    /**
     * @return the listadoalumnos
     */
    public javax.swing.JComboBox<String> getListadoalumnos() {
        return listadoalumnos;
    }

    /**
     * @param listadoalumnos the listadoalumnos to set
     */
    public void setListadoalumnos(javax.swing.JComboBox<String> listadoalumnos) {
        this.listadoalumnos = listadoalumnos;
    }

    /**
     * @return the textoemail
     */
    public javax.swing.JTextField getTextoemail() {
        return textoemail;
    }

    /**
     * @param textoemail the textoemail to set
     */
    public void setTextoemail(javax.swing.JTextField textoemail) {
        this.textoemail = textoemail;
    }

    /**
     * @return the textonombre
     */
    public javax.swing.JTextField getTextonombre() {
        return textonombre;
    }

    /**
     * @param textonombre the textonombre to set
     */
    public void setTextonombre(javax.swing.JTextField textonombre) {
        this.textonombre = textonombre;
    }

    /**
     * @return the textotelefono
     */
    public javax.swing.JTextField getTextotelefono() {
        return textotelefono;
    }

    /**
     * @param textotelefono the textotelefono to set
     */
    public void setTextotelefono(javax.swing.JTextField textotelefono) {
        this.textotelefono = textotelefono;
    }

    /**
     * @return the hora
     */
    public javax.swing.JComboBox<String> getHora() {
        return hora;
    }

    /**
     * @param hora the hora to set
     */
    public void setHora(javax.swing.JComboBox<String> hora) {
        this.hora = hora;
    }

    /**
     * @return the minutos
     */
    public javax.swing.JComboBox<String> getMinutos() {
        return minutos;
    }

    /**
     * @param minutos the minutos to set
     */
    public void setMinutos(javax.swing.JComboBox<String> minutos) {
        this.minutos = minutos;
    }

    /**
     * @return the botonanularcita
     */
    public javax.swing.JButton getBotonanularcita() {
        return botonanularcita;
    }

    /**
     * @param botonanularcita the botonanularcita to set
     */
    public void setBotonanularcita(javax.swing.JButton botonanularcita) {
        this.botonanularcita = botonanularcita;
    }

    /**
     * @return the botonactualizarcita
     */
    public javax.swing.JButton getBotonactualizarcita() {
        return botonactualizarcita;
    }

    /**
     * @param botonactualizarcita the botonactualizarcita to set
     */
    public void setBotonactualizarcita(javax.swing.JButton botonactualizarcita) {
        this.botonactualizarcita = botonactualizarcita;
    }

    /**
     * @return the botonexportaralumnos
     */
    public javax.swing.JButton getBotonexportaralumnos() {
        return botonexportaralumnos;
    }

    /**
     * @param botonexportaralumnos the botonexportaralumnos to set
     */
    public void setBotonexportaralumnos(javax.swing.JButton botonexportaralumnos) {
        this.botonexportaralumnos = botonexportaralumnos;
    }

    /**
     * @return the botonexportarcitas
     */
    public javax.swing.JButton getBotonexportarcitas() {
        return botonexportarcitas;
    }

    /**
     * @param botonexportarcitas the botonexportarcitas to set
     */
    public void setBotonexportarcitas(javax.swing.JButton botonexportarcitas) {
        this.botonexportarcitas = botonexportarcitas;
    }

    /**
     * @return the botonimportaralumnos
     */
    public javax.swing.JButton getBotonimportaralumnos() {
        return botonimportaralumnos;
    }

    /**
     * @param botonimportaralumnos the botonimportaralumnos to set
     */
    public void setBotonimportaralumnos(javax.swing.JButton botonimportaralumnos) {
        this.botonimportaralumnos = botonimportaralumnos;
    }

    /**
     * @return the botonimportarcitas
     */
    public javax.swing.JButton getBotonimportarcitas() {
        return botonimportarcitas;
    }

    /**
     * @param botonimportarcitas the botonimportarcitas to set
     */
    public void setBotonimportarcitas(javax.swing.JButton botonimportarcitas) {
        this.botonimportarcitas = botonimportarcitas;
    }

    /**
     * @return the selectorfichero
     */
    public javax.swing.JFileChooser getSelectorfichero() {
        return selectorfichero;
    }

    /**
     * @param selectorfichero the selectorfichero to set
     */
    public void setSelectorfichero(javax.swing.JFileChooser selectorfichero) {
        this.selectorfichero = selectorfichero;
    }

    /**
     * @return the botonjavadoc
     */
    public javax.swing.JButton getBotonjavadoc() {
        return botonjavadoc;
    }

    /**
     * @param botonjavadoc the botonjavadoc to set
     */
    public void setBotonjavadoc(javax.swing.JButton botonjavadoc) {
        this.botonjavadoc = botonjavadoc;
    }
    
}
